Graph options v2
sanderl/calculator pull request #3
Opened 2019-12-14 13:32 UTC by rudyhuyn

### Description of the changes:
- Add GraphSettingsViewModel to simplify the UI part of the control and manage all the logic
- Manage error states
- Disable keyboard when the flyout is opened
- [Optimization] Only load GraphSettings after the user clicks on the button 
- Keep default styling of textbox in GraphSettings
- Use TextBlock::Header instead of a TextBlock
- Add a 1px margin between radiobutton/togglebutton to improve the readability of the UI
- Tweak a little the graph buttons

### How changes were validated:
- Manually

2019-12-15 16:52 UTC, sanderl commented on src/CalcViewModel/GraphingCalculator/GraphingSettingsViewModel.cpp
> +#include "pch.h"
Needs a copyright header.

2019-12-15 16:54 UTC, sanderl commented on src/Calculator/GraphingSettingsViewModel.cpp
> +#include "pch.h"
do you still need this file?

2019-12-15 16:54 UTC, sanderl commented on src/Calculator/GraphingSettingsViewModel.h
> +#pragma once
Do you need this file?

2019-12-15 16:57 UTC, sanderl commented on src/Calculator/Views/GraphingCalculator/GraphingSettings.xaml.cpp
>  #include "CalcViewModel\Common\AppResourceProvider.cpp"
Copyright header

2019-12-15 16:58 UTC, sanderl commented on src/Calculator/Views/GraphingCalculator/GraphingSettings.xaml.h
>  #pragma once
copyright header

2019-12-15 17:14 UTC, sanderl requested changes
I did a buddy build and a buddy test. A few things I noticed:
1. For the error state, the background should change to red like the EquationTextBox
2. I noticed sometimes the grid doesn't update according to the options set by the user. 
I graphed sin(x), I noticed the grid options did not reflect what was shown on the graph (it showed -12 and 12 for x and -10 and 10 for y). I pressed enter to get the graph to reset and nothing happened. The graph showed the axes at -1000 to 1000. 

I like that you pulled most of the logic into a VM. I think that is the right design.

I made a few comments about extra files and missing headers.

2019-12-16 09:05 UTC, rudyhuyn commented on src/Calculator/GraphingSettingsViewModel.cpp
> +#include "pch.h"
No

2019-12-16 09:56 UTC, rudyhuyn commented
Thank you for your feedback! Copyright added and extra file removed!

I've also fixed some issues with high contrast: ChromeWhiteHighControlSelectedForegroundBrush was missing in HighContrast and the toggle button in GraphControl had some issues.

I've also replaced all brushes specially created for the fake Toggle Button in Graph Settings by the brushes used in the real ToggleButton to always be consistent with the system.

2020-01-16 18:28 UTC, closed without merging